require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompanyCountriesController do

  # This should return the minimal set of attributes required to create a valid
  # CompanyCountry. As you add validations to CompanyCountry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompanyCountriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all company_countries as @company_countries" do
      company_country = CompanyCountry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:company_countries).should eq([company_country])
    end
  end

  describe "GET show" do
    it "assigns the requested company_country as @company_country" do
      company_country = CompanyCountry.create! valid_attributes
      get :show, {:id => company_country.to_param}, valid_session
      assigns(:company_country).should eq(company_country)
    end
  end

  describe "GET new" do
    it "assigns a new company_country as @company_country" do
      get :new, {}, valid_session
      assigns(:company_country).should be_a_new(CompanyCountry)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_country as @company_country" do
      company_country = CompanyCountry.create! valid_attributes
      get :edit, {:id => company_country.to_param}, valid_session
      assigns(:company_country).should eq(company_country)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompanyCountry" do
        expect {
          post :create, {:company_country => valid_attributes}, valid_session
        }.to change(CompanyCountry, :count).by(1)
      end

      it "assigns a newly created company_country as @company_country" do
        post :create, {:company_country => valid_attributes}, valid_session
        assigns(:company_country).should be_a(CompanyCountry)
        assigns(:company_country).should be_persisted
      end

      it "redirects to the created company_country" do
        post :create, {:company_country => valid_attributes}, valid_session
        response.should redirect_to(CompanyCountry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_country as @company_country" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyCountry.any_instance.stub(:save).and_return(false)
        post :create, {:company_country => {}}, valid_session
        assigns(:company_country).should be_a_new(CompanyCountry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyCountry.any_instance.stub(:save).and_return(false)
        post :create, {:company_country => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_country" do
        company_country = CompanyCountry.create! valid_attributes
        # Assuming there are no other company_countries in the database, this
        # specifies that the CompanyCountry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompanyCountry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => company_country.to_param, :company_country => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested company_country as @company_country" do
        company_country = CompanyCountry.create! valid_attributes
        put :update, {:id => company_country.to_param, :company_country => valid_attributes}, valid_session
        assigns(:company_country).should eq(company_country)
      end

      it "redirects to the company_country" do
        company_country = CompanyCountry.create! valid_attributes
        put :update, {:id => company_country.to_param, :company_country => valid_attributes}, valid_session
        response.should redirect_to(company_country)
      end
    end

    describe "with invalid params" do
      it "assigns the company_country as @company_country" do
        company_country = CompanyCountry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyCountry.any_instance.stub(:save).and_return(false)
        put :update, {:id => company_country.to_param, :company_country => {}}, valid_session
        assigns(:company_country).should eq(company_country)
      end

      it "re-renders the 'edit' template" do
        company_country = CompanyCountry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyCountry.any_instance.stub(:save).and_return(false)
        put :update, {:id => company_country.to_param, :company_country => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_country" do
      company_country = CompanyCountry.create! valid_attributes
      expect {
        delete :destroy, {:id => company_country.to_param}, valid_session
      }.to change(CompanyCountry, :count).by(-1)
    end

    it "redirects to the company_countries list" do
      company_country = CompanyCountry.create! valid_attributes
      delete :destroy, {:id => company_country.to_param}, valid_session
      response.should redirect_to(company_countries_url)
    end
  end

end
