require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailInRebateStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # MailInRebateStatus. As you add validations to MailInRebateStatus, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailInRebateStatusesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mail_in_rebate_statuses as @mail_in_rebate_statuses" do
      mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mail_in_rebate_statuses).should eq([mail_in_rebate_status])
    end
  end

  describe "GET show" do
    it "assigns the requested mail_in_rebate_status as @mail_in_rebate_status" do
      mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
      get :show, {:id => mail_in_rebate_status.to_param}, valid_session
      assigns(:mail_in_rebate_status).should eq(mail_in_rebate_status)
    end
  end

  describe "GET new" do
    it "assigns a new mail_in_rebate_status as @mail_in_rebate_status" do
      get :new, {}, valid_session
      assigns(:mail_in_rebate_status).should be_a_new(MailInRebateStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested mail_in_rebate_status as @mail_in_rebate_status" do
      mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
      get :edit, {:id => mail_in_rebate_status.to_param}, valid_session
      assigns(:mail_in_rebate_status).should eq(mail_in_rebate_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailInRebateStatus" do
        expect {
          post :create, {:mail_in_rebate_status => valid_attributes}, valid_session
        }.to change(MailInRebateStatus, :count).by(1)
      end

      it "assigns a newly created mail_in_rebate_status as @mail_in_rebate_status" do
        post :create, {:mail_in_rebate_status => valid_attributes}, valid_session
        assigns(:mail_in_rebate_status).should be_a(MailInRebateStatus)
        assigns(:mail_in_rebate_status).should be_persisted
      end

      it "redirects to the created mail_in_rebate_status" do
        post :create, {:mail_in_rebate_status => valid_attributes}, valid_session
        response.should redirect_to(MailInRebateStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mail_in_rebate_status as @mail_in_rebate_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailInRebateStatus.any_instance.stub(:save).and_return(false)
        post :create, {:mail_in_rebate_status => {}}, valid_session
        assigns(:mail_in_rebate_status).should be_a_new(MailInRebateStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailInRebateStatus.any_instance.stub(:save).and_return(false)
        post :create, {:mail_in_rebate_status => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mail_in_rebate_status" do
        mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
        # Assuming there are no other mail_in_rebate_statuses in the database, this
        # specifies that the MailInRebateStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MailInRebateStatus.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mail_in_rebate_status.to_param, :mail_in_rebate_status => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mail_in_rebate_status as @mail_in_rebate_status" do
        mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
        put :update, {:id => mail_in_rebate_status.to_param, :mail_in_rebate_status => valid_attributes}, valid_session
        assigns(:mail_in_rebate_status).should eq(mail_in_rebate_status)
      end

      it "redirects to the mail_in_rebate_status" do
        mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
        put :update, {:id => mail_in_rebate_status.to_param, :mail_in_rebate_status => valid_attributes}, valid_session
        response.should redirect_to(mail_in_rebate_status)
      end
    end

    describe "with invalid params" do
      it "assigns the mail_in_rebate_status as @mail_in_rebate_status" do
        mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailInRebateStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => mail_in_rebate_status.to_param, :mail_in_rebate_status => {}}, valid_session
        assigns(:mail_in_rebate_status).should eq(mail_in_rebate_status)
      end

      it "re-renders the 'edit' template" do
        mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailInRebateStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => mail_in_rebate_status.to_param, :mail_in_rebate_status => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mail_in_rebate_status" do
      mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
      expect {
        delete :destroy, {:id => mail_in_rebate_status.to_param}, valid_session
      }.to change(MailInRebateStatus, :count).by(-1)
    end

    it "redirects to the mail_in_rebate_statuses list" do
      mail_in_rebate_status = MailInRebateStatus.create! valid_attributes
      delete :destroy, {:id => mail_in_rebate_status.to_param}, valid_session
      response.should redirect_to(mail_in_rebate_statuses_url)
    end
  end

end
