require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PurchaseFeedbacksController do

  # This should return the minimal set of attributes required to create a valid
  # PurchaseFeedback. As you add validations to PurchaseFeedback, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PurchaseFeedbacksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all purchase_feedbacks as @purchase_feedbacks" do
      purchase_feedback = PurchaseFeedback.create! valid_attributes
      get :index, {}, valid_session
      assigns(:purchase_feedbacks).should eq([purchase_feedback])
    end
  end

  describe "GET show" do
    it "assigns the requested purchase_feedback as @purchase_feedback" do
      purchase_feedback = PurchaseFeedback.create! valid_attributes
      get :show, {:id => purchase_feedback.to_param}, valid_session
      assigns(:purchase_feedback).should eq(purchase_feedback)
    end
  end

  describe "GET new" do
    it "assigns a new purchase_feedback as @purchase_feedback" do
      get :new, {}, valid_session
      assigns(:purchase_feedback).should be_a_new(PurchaseFeedback)
    end
  end

  describe "GET edit" do
    it "assigns the requested purchase_feedback as @purchase_feedback" do
      purchase_feedback = PurchaseFeedback.create! valid_attributes
      get :edit, {:id => purchase_feedback.to_param}, valid_session
      assigns(:purchase_feedback).should eq(purchase_feedback)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PurchaseFeedback" do
        expect {
          post :create, {:purchase_feedback => valid_attributes}, valid_session
        }.to change(PurchaseFeedback, :count).by(1)
      end

      it "assigns a newly created purchase_feedback as @purchase_feedback" do
        post :create, {:purchase_feedback => valid_attributes}, valid_session
        assigns(:purchase_feedback).should be_a(PurchaseFeedback)
        assigns(:purchase_feedback).should be_persisted
      end

      it "redirects to the created purchase_feedback" do
        post :create, {:purchase_feedback => valid_attributes}, valid_session
        response.should redirect_to(PurchaseFeedback.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved purchase_feedback as @purchase_feedback" do
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseFeedback.any_instance.stub(:save).and_return(false)
        post :create, {:purchase_feedback => {}}, valid_session
        assigns(:purchase_feedback).should be_a_new(PurchaseFeedback)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseFeedback.any_instance.stub(:save).and_return(false)
        post :create, {:purchase_feedback => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested purchase_feedback" do
        purchase_feedback = PurchaseFeedback.create! valid_attributes
        # Assuming there are no other purchase_feedbacks in the database, this
        # specifies that the PurchaseFeedback created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PurchaseFeedback.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => purchase_feedback.to_param, :purchase_feedback => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested purchase_feedback as @purchase_feedback" do
        purchase_feedback = PurchaseFeedback.create! valid_attributes
        put :update, {:id => purchase_feedback.to_param, :purchase_feedback => valid_attributes}, valid_session
        assigns(:purchase_feedback).should eq(purchase_feedback)
      end

      it "redirects to the purchase_feedback" do
        purchase_feedback = PurchaseFeedback.create! valid_attributes
        put :update, {:id => purchase_feedback.to_param, :purchase_feedback => valid_attributes}, valid_session
        response.should redirect_to(purchase_feedback)
      end
    end

    describe "with invalid params" do
      it "assigns the purchase_feedback as @purchase_feedback" do
        purchase_feedback = PurchaseFeedback.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseFeedback.any_instance.stub(:save).and_return(false)
        put :update, {:id => purchase_feedback.to_param, :purchase_feedback => {}}, valid_session
        assigns(:purchase_feedback).should eq(purchase_feedback)
      end

      it "re-renders the 'edit' template" do
        purchase_feedback = PurchaseFeedback.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseFeedback.any_instance.stub(:save).and_return(false)
        put :update, {:id => purchase_feedback.to_param, :purchase_feedback => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested purchase_feedback" do
      purchase_feedback = PurchaseFeedback.create! valid_attributes
      expect {
        delete :destroy, {:id => purchase_feedback.to_param}, valid_session
      }.to change(PurchaseFeedback, :count).by(-1)
    end

    it "redirects to the purchase_feedbacks list" do
      purchase_feedback = PurchaseFeedback.create! valid_attributes
      delete :destroy, {:id => purchase_feedback.to_param}, valid_session
      response.should redirect_to(purchase_feedbacks_url)
    end
  end

end
